### ISSUE TITLE
Step by step guide for creating the stopwatch

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-stopwatch#1]
Create the Elixir/Phoenix version of https://github.com/dwyl/stopwatch using LiveView.
- Use `mount` to initialise the timer state and start `:timer` on server
- Use `handle_info` to list to the timer event
- Send new timer state to client

Inspired by: https://elixirforum.com/t/livecomponent-updating-itself-at-regular-intervals/37047/8

**Comment by SimonLab** [comment]
# Create new Phoenix `stopwatch` app :stopwatch: 
Run `mix phx.new stopwatch --no-ecto --no-mailer --no-dashboard --no-gettext`
Run `mix help phx.new` to see the documentation and list of options for `phx.new` command
Install dependencies, then `cd stopwatch` and make sure the tests are passing `mix test` and the application is running `mix phx.server`

# Create liveview structure:
- Create live folder for liveview controllers: `mkdir lib/stopwatch_web/live`
- Create controller for liveview: `touch lib/stopwatch_web/live/stopwatch_live.ex` This is where the liveview logic happen
- Create view view file for liveview templates: `touch lib/stopwatch_web/views/stopwatch_view.ex`
- Create new template folder for liveview templates: `mkdir lib/stopwatch_web/templates/stopwatch`
- Finally create the template file itself: `touch lib/stopwatch_web/templates/stopwatch/stopwatch.html.heex`

See doc about [colocating section](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-colocating-templates) 

# Update created files above to make liveview magic happen

**Comment by nelsonic** [comment]
@SimonLab have you looked at using `Alpine.js` for the counter bit? 
If not, I was thinking of adding a basic stopwatch in `Alpine` + `Tailwind` now.

**Comment by nelsonic** [comment]
@SimonLab OK, cool. gonna take a look at this: https://github.com/dwyl/learn-alpine.js/issues/2 ⏳

**Comment by SimonLab** [comment]
I've created a draft PR which initialised the Phoenix application and I've updated the Readme with the steps to create the stopwatch, still need to:

- [ ] Follow the steps on the Readme and update the Phoenix code
- [ ] Add Github CI to run the tests on Github
- [ ] Deploy the application on Fly
- [ ] Update the tests

**Comment by SimonLab** [comment]
Application deployed on https://liveview-stopwatch.fly.dev/

**Comment by nelsonic** [comment]
@SimonLab same: https://dwyl.github.io/learn-alpine.js/stopwatch.html

**Comment by nelsonic** [comment]
Pretty confident I/we could integrate **`Alpine.js`** into the **`LiveView`** stopwatch 
and only send the `start|stop` time and events to the server for synch to connected clients.

**Comment by nelsonic** [comment]
@SimonLab your PR #2 is merged. Anything else to do for this issue? 💭

**Comment by SimonLab** [comment]
I think we can close this issue now and focus on #3
