### ISSUE TITLE
Chore: Enhance `README.md` with Context, Screenshots and Conclusion

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-stopwatch#3]
At present, the `README.md` shows basic setup of the App. 🎉 

The barebones stopwatch _works_: https://liveview-stopwatch.fly.dev/ 🚀 

![image](https://user-images.githubusercontent.com/194400/174234916-dcbd93d6-70a8-448b-870e-d62df1adfe4b.png)

But does not take _advantage_ of the "killer feature" of `LiveView` ... 🔄 
i.e. "free" RealTime Sync between clients! 🤯 😍 

# Todo

Add:
+ [x] **Context** to _why_ we (or anyone `else`) would want to use `LiveView` to build a Stopwatch.
+ [x] **`Reset`** button similar to https://github.com/dwyl/learn-alpine.js/issues/2#issuecomment-1157886870
+ [x] ***Sync*** between clients
+ [x] ***Screenshot***(s) of the app in action
+ [x] **_Future_ enhancements** - what ***`else`*** would we like to add to this?

**Comment by nelsonic** [comment]
@SimonLab do you want to take a look at this or should I make an attempt while you 
review the PRs assigned to you: https://github.com/pulls?q=is%3Aopen+is%3Apr+assignee%3ASimonLab ?

https://github.com/orgs/dwyl/projects/14?fullscreen=true 
![image](https://user-images.githubusercontent.com/194400/174236362-15db1c91-5095-4baf-8eaa-ca588ad4596b.png)

**Comment by nelsonic** [comment]
Gonna time-box **`T1h`** on this and see how far I get. ⏳ 
Keen to have at least the RealTime Sync between clients and a Screenshot in the `README.md`. 💭 
Will create a PR even if I don't _finish_ it now it will be a starting point. 👍

**Comment by SimonLab** [comment]
Do you have a specific implementation in mind for RealTime Sync @nelsonic ?
We could start by using `PubSub` and add persistence with Postges (or ets if we don't want to persist the timers in database)

**Comment by nelsonic** [comment]
@SimonLab good question.
I was thinking just the same methodology we used in the **`Counter`** App: [dwyl/phoenix-liveview-counter-tutorial](https://github.com/dwyl/phoenix-liveview-counter-tutorial)
but just the `PubSub` part, I don't even think we _need_ persistence right now.
That's the kind of thing we can just _describe_ in the "potential enhancements" section.

**Comment by SimonLab** [comment]
Sounds good. I would even maybe use `Agent` instead of `GenServer` as the state of the Timer is simple.
Agree to delay persistence for a future feature.

**Comment by nelsonic** [comment]
@SimonLab yeah, an `Agent` is a good option. 
Provided we can send the:  
+ `start` and `stop` time 
+ signals/actions (`start|stop|reset`) 
over the socket we have a _collaborative_ stopwatch.

Not saying I don't _want_ to have persistence.
In fact if we can add **`auth`** and **`history`** it would be _amaze_. 
But one thing at a time. 👍

**Comment by SimonLab** [comment]
stopwatch sync PR ready: #5 
I'll add the reset button and logic on a next PR

**Comment by nelsonic** [comment]
![stopwatch](https://user-images.githubusercontent.com/194400/174432051-5199369d-df07-4809-a758-24d3738535f7.png)

**Comment by nelsonic** [comment]
@SimonLab please see: #4 🙏 Thanks! ☀️ [when you are back at your desk on Monday!]

**Comment by SimonLab** [comment]
Readme is up to date, and sync is now working, closing

**Comment by nelsonic** [comment]
Thanks @SimonLab 🚀
